
package spaceinvaders;

import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;


public class Facil extends javax.swing.JFrame {

    String navecita1,nombre, colorlaser;
    Timer timer;
    JLabel marciano[] = new JLabel[19];

    public Facil(String navecita1,String nombre) {
        initComponents();
        this.navecita1=navecita1;
        this.nombre=nombre;
        switch (navecita1){
            case "roja":
                navecita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naves/playerShip2_red.png")));
                colorlaser = "/lasers/laserRed01.png";
            break;
            
            case "azul":
                navecita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naves/playerShip2_blue.png")));
                colorlaser = "/lasers/laserBlue16.png";
                break;
     
            case "verde":
                navecita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naves/playerShip2_green.png")));
                colorlaser = "/lasers/laserGreen11.png";
                break;
            case "naranja":
                navecita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naves/playerShip2_orange.png")));
                colorlaser = "/lasers/fire06.png";
                break;       
        }
        int y = 0, l = 0;
        for (int i = 1; i <= 2; i++) {
            int x = 60; 
            for (int j = 1; j <= 9; j++) {
                l = l+1;
                marciano[l] = new JLabel();
                marciano[l].setSize(120, 150);
                marciano[l].setIcon(new javax.swing.ImageIcon(getClass().getResource("/naves/playerShip2_orange.png")));
                marciano[l].setLocation(x, y);
                jPanel1.add(marciano[l], 1);
                jPanel1.validate();
                x = x+60;  
            }
            y = y+60;
        }
        Timer movimiento = new Timer();
        TimerTask mov = new TimerTask(){
            JLabel marcianos;
            int y_marciano;
            int x_marciano;
            int tod;
            @Override
            public void run(){
                for (int i = 1; i <= 18; i++){
                    JLabel marcianos = marciano[i];
                    x_marciano = marcianos.getX();
                    y_marciano = marcianos.getY();
                    if (x_marciano == 0){
                        tod = 1;
                    }
                    if (x_marciano == 600){
                        tod = 0;
                    }
                    
                }
                if (tod == 0){
                    for (int i = 1; i <= 18; i++){
                    JLabel marcianos = marciano[i];
                    x_marciano = marcianos.getX();
                    y_marciano = marcianos.getY();
                    x_marciano -=60;
                    marcianos.setLocation(x_marciano, y_marciano); 
                    }
                }
                if (tod == 1){
                    for (int i = 1; i <= 18; i++){
                    JLabel marcianos = marciano[i];
                    x_marciano = marcianos.getX();
                    y_marciano = marcianos.getY();
                    x_marciano +=60;
                    marcianos.setLocation(x_marciano, y_marciano); 
                    }
                }
            }
        };
        movimiento.schedule(mov, 1000, 1000);       
}
            

    private Facil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navecita = new javax.swing.JLabel();
        JLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(710, 500));
        jPanel1.setLayout(null);
        jPanel1.add(navecita);
        navecita.setBounds(300, 350, 120, 130);

        JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/facil1.gif"))); // NOI18N
        JLabel.setPreferredSize(new java.awt.Dimension(710, 500));
        jPanel1.add(JLabel);
        JLabel.setBounds(0, 0, 750, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 520);

        setSize(new java.awt.Dimension(734, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int x_nav = navecita.getX();
        int y_nav = navecita.getY();
        
        
        if (evt.getKeyChar() == 'a' || evt.getKeyChar() == 'A' || evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            if(x_nav>0){
                x_nav -= 60;
                navecita.setLocation(x_nav, y_nav);  
            }
        }
        
        if (evt.getKeyChar() == 'd' || evt.getKeyChar() == 'D' || evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            if(x_nav<600){
                x_nav += 60;
                navecita.setLocation(x_nav, y_nav);
            }
        }
        
        if(evt.getKeyChar() == 'w' || evt.getKeyChar() == 'W' || evt.getExtendedKeyCode() == KeyEvent.VK_UP){

            JLabel laserxd = new JLabel();
            laserxd.setLocation(navecita.getX()+50, navecita.getY()+40);
            laserxd.setIcon(new javax.swing.ImageIcon(getClass().getResource(colorlaser)));
            laserxd.setSize(20, 60);
            jPanel1.add(laserxd, 1);
            jPanel1.validate();
            Timer time = new Timer();
            TimerTask task = new TimerTask(){
                int y_laser = laserxd.getY();
                int x_laser = laserxd.getX();
                @Override
                public void run(){
                    if (y_laser > -60){
                        y_laser = y_laser - 10;
                        laserxd.setLocation(x_laser, y_laser);
                    }  else{
                        time.cancel();
                        jPanel1.remove(laserxd);
                    }
                           
                }
            };
            time.schedule(task, 0, 40);
        }
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel navecita;
    // End of variables declaration//GEN-END:variables

}
